### ISSUE TITLE
Activate code coverage

### ISSUE THREAD

**Issue by gdalle** [yanwu-728/JuliaOptimizationChallenge.jl#15]
https://github.com/yanwu-728/JuliaOptimizationChallenge.jl/blob/912b0542c84f7c5d201b7279155f7f552fff0de4/README.md?plain=1#L5

If you want this to be useful, you need to give CodeCov read access to this GitHub repository

**Comment by DVILL17** [comment]
Code coverage shows up as unknown in the readme, but it shows the results when we click on the link. What are we missing?

**Comment by gdalle** [comment]
It was just a matter of refreshing
